version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/dashboard"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  qdrant_data: